---
title: "Inference II Simulation"
author: "Andy Shi"
date: "May 8, 2018"
output: pdf_document
---

```{r libraries}
library(mixtools)
library(ggplot2)
library(reshape2)
library(cowplot)
library(matrixStats)
library(gridExtra)
library(xtable)
```

# EM vs. Monte Carlo EM

```{r monte-carlo-em}
# monte carlo EM for gaussian mixtures.
# adapted from normalmixEM2comp from mixtools package
normalmix_mcem <- function (x, lambda = NULL, mu = NULL, sigsqrd = NULL,
                            eps = 1e-08, maxit = 1000,
                            verb = FALSE, mc_samp = 100) {
    x <- as.vector(x)
    s <- NULL
    if (!is.null(sigsqrd)) {
        s <- sqrt(sigsqrd)
    }
    tmp <- normalmix.init(x = x, lambda = lambda, mu = mu, s = s,
                          k = 2, arbmean = TRUE, arbvar = TRUE)
    lambda <- tmp$lambda[1]
    mu <- tmp$mu
    sigma <- tmp$s
    sigsqrd <- sigma^2
    arbvar <- (length(sigsqrd) == 2)
    mu1 <- mu[1]
    mu2 <- mu[2]
    sigsqrd1 <- sigsqrd[1]
    sigsqrd2 <- sigsqrd[arbvar + 1]
    mx <- mean(x)
    n <- length(x)
    const <- n * 0.918938533204673
    dl <- 1 + eps
    iter <- 0
    ll <- rep(0, maxit + 1)
    a1 <- (x - mu1)^2
    b1 <- (lambda/sqrt(sigsqrd1)) * exp(-a1/2/sigsqrd1)
    a2 <- (x - mu2)^2
    b2 <- ((1 - lambda)/sqrt(sigsqrd2)) * exp(-a2/2/sigsqrd2)
    l <- sum(log(b1 + b2))
    while (dl > eps && iter < maxit) {
        iter <- iter + 1
        ll[iter] <- l
        postprobs1 <- b1/(b1 + b2)
        lambda1 <- mean(postprobs1)
        postprob_sim <- matrix(rbinom(mc_samp * n, size = 1,
                                      prob = rep(postprobs1, mc_samp)),
                               nrow = mc_samp, ncol = n,
                               byrow = TRUE)
        postprobs <- colMeans(postprob_sim)
        lambda <- mean(postprobs)
        mu1 <- mean(postprobs * x)/lambda
        mu2 <- (mx - lambda * mu1)/(1 - lambda)
        if (arbvar) {
            sigsqrd1 <- mean(postprobs * a1)/lambda
            sigsqrd2 <- mean((1 - postprobs) * a2)/(1 - lambda)
        }
        else {
            sigsqrd1 <- sigsqrd2 <- mean(postprobs * a1 + (1 -  postprobs) * a2)
        }
        a1 <- (x - mu1)^2
        b1 <- (lambda/sqrt(sigsqrd1)) * exp(-a1/2/sigsqrd1)
        a2 <- (x - mu2)^2
        b2 <- ((1 - lambda)/sqrt(sigsqrd2)) * exp(-a2/2/sigsqrd2)
        oldl <- l
        l <- sum(log(b1 + b2))
        dl <- l - oldl
        if (verb) {
            cat("iteration =", iter, " log-lik diff =", dl, " log-lik =",
                l - const, "\n")
        }
    }
    cat("number of iterations=", iter, "\n")
    iter <- iter + 1
    ll[iter] <- l
    postprobs <- cbind(postprobs, 1 - postprobs)
    colnames(postprobs) <- c(paste("comp", ".", 1:2, sep = ""))
    out <- list(x = x, lambda = c(lambda, 1 - lambda),
                mu = c(mu1,  mu2),
                sigma = sqrt(c(sigsqrd1, sigsqrd2)[1:(1 + arbvar)]),
                loglik = l - const, posterior = postprobs, all.loglik = ll[1:iter] -
                    const, restarts = 0, ft = "normalmixEM")
    class(out) <- "mixEM"
    out
}
```

```{r traditional-em, cache = TRUE}
attach(faithful)
wait1 <- normalmixEM(waiting, lambda = .5, mu = c(55, 80), sigma = c(5,5))
plot(wait1, density = TRUE, cex.axis = 1.4, cex.lab = 1.5, cex.main = 1.5,
     main2 = "Time between Old Faithful eruptions", xlab2 = "Minutes", whichplots = 2)

# simulations
set.seed(11)
numSims = 100
numObs = 1000
x = NULL
x = rnormmix(n=numObs*numSims,lambda = c(0.3,0.7),mu=c(5,10),sigma=c(2,3)) # generate the data
matrix_results_normalEM = matrix(0,nrow = numSims,ncol = 8)
matrix_results_mcem = matrix(NA, nrow = numSims, ncol = 8)

for (i in 1:numSims){
    # 1- 1000, 1001-2000, 2001-3000,...
  time_em = system.time({
      normalEM = normalmixEM(x[(numObs*(i-1)+1):(numObs*(i))],maxit = 10000)
  })
  time_mcem = system.time({
      mcem = normalmix_mcem(x[(numObs*(i-1)+1):(numObs*(i))],maxit = 10000)
  })
  matrix_results_normalEM[i,1:2] = normalEM$lambda
  matrix_results_normalEM[i,3:4] = normalEM$mu
  matrix_results_normalEM[i,5:6] = normalEM$sigma
  matrix_results_normalEM[i,7] = length(normalEM$all.loglik)
  matrix_results_normalEM[i,8] = time_em[3]
  
  matrix_results_mcem[i, 1:2] = mcem$lambda
  matrix_results_mcem[i, 3:4] = mcem$mu
  matrix_results_mcem[i, 5:6] = mcem$sigma
  matrix_results_mcem[i, 7] = length(mcem$all.loglik)
  matrix_results_mcem[i, 8] = time_mcem[3]
  
}

dataframe_results_normalEM = as.data.frame(matrix_results_normalEM)
colnames(dataframe_results_normalEM) = c("lambda1","lambda2","mu1","mu2",
                                         "sigma1","sigma2","numIters","timing")
dataframe_results_mcem = as.data.frame(matrix_results_mcem)
colnames(dataframe_results_mcem) = c("lambda1","lambda2","mu1","mu2",
                                         "sigma1","sigma2","numIters","timing")

summary(dataframe_results_normalEM$timing)
summary(dataframe_results_mcem$timing)

dataframe_results_normalEM$simulations = seq(1,numSims)
melted_df = melt(dataframe_results_normalEM[,-7],id.vars = "simulations")
melted_df$method = rep("normalEM",length(melted_df$simulations))
p <- ggplot(melted_df) + geom_violin(aes(factor(variable), value,fill=factor(method))) +
    ylab("Value") + xlab("") +
    geom_segment(aes(x = 0.5, y = 0.3, xend = 1.5, yend = 0.3,col="red")) +
    geom_segment(aes(x = 1.5, y = 0.7, xend = 2.5, yend = 0.7,col="red"))+
    geom_segment(aes(x = 2.5, y = 5, xend = 3.5, yend = 5,col="red"))+
    geom_segment(aes(x = 3.5, y = 10, xend = 4.5, yend = 10,col="red"))+
    geom_segment(aes(x = 4.5, y = 2, xend = 5.5, yend = 2,col="red"))+
    geom_segment(aes(x = 5.5, y = 3, xend = 6.5, yend = 3,col="red")) +
    guides(col=FALSE)
ggsave(p,filename="Simulation_Setup1.pdf",width=11,height = 8,units = "in")

```


## Simulated Data: Univariate

## Simulated Data: Multivariate

## Real Data: Old Faithful

# GLMM: MCEM vs. Gauss-Hermite

```{r}
load("sim_K10.RData")
load("sim_K50.RData")

# it is in gh_beta0, gh_beta1, mcem_beta0, and mcem_beta1

dataframe_results_MCEM = as.data.frame(out_K10)
dataframe_results_MCEM_K50 = as.data.frame(out_K50)

dataframe_results_MCEM$simulations = seq(1,100)
dataframe_results_MCEM_K50$simulations = seq(1,100)

dataframe_MCEM = dataframe_results_MCEM[,c(1,2,7,8,13)]
dataframe_results_MCEM_K50 = dataframe_results_MCEM_K50[,c(1,2,7,8,13)]

rownames(dataframe_MCEM) = seq(1,100)
rownames(dataframe_results_MCEM_K50) = seq(1,100)

melted_df = melt(dataframe_MCEM,id.vars = "simulations")
melted_df$variable = factor(melted_df$variable,levels=c("gh_beta0","mcem_beta0",
                                                        "gh_beta1","mcem_beta1"))
melted_df$variable_type = c(rep("beta0",100),rep("beta1",100),
                            rep("beta0",100),rep("beta1",100))
melted_df$method = c(rep("GH",200),rep("MCEM",200))

melted_df_K50 = melt(dataframe_results_MCEM_K50,id.vars = "simulations")
melted_df_K50$variable = factor(melted_df_K50$variable,levels=c("gh_beta0","mcem_beta0",
                                                        "gh_beta1","mcem_beta1"))
melted_df_K50$variable_type = c(rep("beta0",100),rep("beta1",100),
                            rep("beta0",100),rep("beta1",100))
melted_df_K50$method = c(rep("GH",200),rep("MCEM",200))

p_K10 <- ggplot(melted_df) + geom_violin(aes(factor(variable_type), value, fill=factor(method))) +
    ylab("Value") + xlab("") +
    geom_segment(aes(x = 0.5, y = log(0.25), xend = 1.5, yend = log(0.25)),col="navy") +
    geom_segment(aes(x = 1.5, y = log(2), xend = 2.5, yend =log(2)),col="navy")+
    guides(col=FALSE) + ggtitle("K=10") + theme(legend.position="none")

p_K10_zoom <- ggplot(melted_df) + geom_violin(aes(factor(variable_type), value, fill=factor(method))) +
    ylab("Value") + xlab("") +
    geom_segment(aes(x = 0.5, y = log(0.25), xend = 1.5, yend = log(0.25)),col="navy") +
    geom_segment(aes(x = 1.5, y = log(2), xend = 2.5, yend =log(2)),col="navy")+
    guides(col=FALSE) + ggtitle("K=10") + theme(legend.position="none") +
    coord_cartesian(ylim=c(-2.5,1.5))

p_K50 <- ggplot(melted_df_K50) + geom_violin(aes(factor(variable_type), value, fill=factor(method))) +
    ylab("Value") + xlab("") +
    geom_segment(aes(x = 0.5, y = log(0.25), xend = 1.5, yend = log(0.25)),col="navy") +
    geom_segment(aes(x = 1.5, y = log(2), xend = 2.5, yend =log(2)),col="navy")+
    guides(col=FALSE) + ggtitle("K=50") + coord_cartesian(ylim=c(-2.5,1.5))

p <- grid.arrange(arrangeGrob(p_K10,p_K10_zoom,ncol=2),
         arrangeGrob(p_K50, ncol=1, nrow=1), widths=c(3,3),ncol=2) 

ggsave(p,filename="Simulation_Setup2.pdf",width=11,height = 8,units = "in")


```

## Random intercepts

## Random intercepts and slopes
